name: Build and Release WPF App

on:
  push:
    branches: [main]   

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # or your version

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build the WPF application
        run: dotnet build WpfMVVMProject.sln --configuration Release

    
