name: Release of the Installer

on:
  push:
    tags:
      - "WPFTest-Installer/v*"

env:
  PROJECT_PATH: WpfMVVMProject/WpfMVVMProject.csproj 

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: action/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore ${{ env.PROJECT_PATH }}

      - run: dotnet build ${{ env.PROJECT_PATH }}

      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishingSingleFile=true --no-build
          
